### PR TITLE
Run extension in older version of leetcode

### PR DESCRIPTION
**Pull request by rajatinclude**
Currently this extension only works in newly version of leetcode , when we switch to the old version , it is unable to find the element using html selector , I changed the selected wrt to version .

### CODE REVIEW

**Review by preet-pdf — APPROVED** [review]

**Review by VivekKumar432 — APPROVED** [review]

**Review by sherlockhoe90 — APPROVED** [review]

**Comment by GouravRusiya30** [comment]
Thanks for creating the PR. Can you please add these details in the PR description ?
- Have you tested the changes?
- How have you verified if it is working as expected ?
- Please add snapshots for the reference.

@omkarajagunde Can you please review this PR ?

**Comment by GouravRusiya30** [comment]
Please add relevant snapshots and how you tested your changes.

**Comment by rajatinclude** [comment]
image
In the older version it is showing the companies information , previously it was not showing

**Comment by omkarajagunde** [comment]
Hey @rajatinclude your code changes are working, hence merged, will publish these changes soon to chrome webstore,
thanks for the contribution, Cheers, good day!

**Comment by omkarajagunde** [comment]
FYI: sent for review, will take 3-5 days for fix to be published

**Comment by GouravRusiya30** [comment]
Changes are plublished. Closing this issue.

**Pull request merged**
